articles/urls.py
from django.urls import path

from . import views
app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('search',views.search,name="search"),
    path('<str:article_slug>/', views.read, name="read"),
    path('<str:article_slug>/vote', views.vote, name='vote'),
]

forum/urls.py
from django.urls import path

from . import views
app_name = 'forum'
urlpatterns = [
    path('', views.index,name="index"),
    path('<str:category_slug>/<str:post_slug>',views.post),
    path('<str:category_slug>', views.category),
]

mysite_python/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView



urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'),name='home'),
    url(r'^messages/', include('postman.urls', namespace='postman'),name="postman"),
    path('articles/', include('articles.urls')),
    path('gallery/', include('galery.urls')),
    path('forum/', include('forum.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls,name="admin"),
    path('accounts/', include('django.contrib.auth.urls')),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>  
<script src="{% static 'polls/js/tinymce/tinymce.min.js' %}"></script>
<script type="text/javascript" src="{% static 'polls/js/tinymce/custom.js' %}" ></script>
<link rel="stylesheet" type="text/css" href="{% static 'polls/blog.css' %}" />
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <a class="navbar-brand" href="{% url 'home' %}">Iforum</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Accueil <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active"><a href="{% url 'articles:index' %}" class="nav-link">Articles</a></li>
                  <li class="nav-item active"><a href="{% url 'forum:index' %}" class="nav-link">Forum</a></li>
                  {% if request.user.is_staff %}
                    <li class="nav-item active"><a href="{% url 'admin:index' %}" class="nav-link">Administration</a></li>
                  {% endif %}
                  <li class="nav-item active"><a href="" class="nav-link"></a></li>
              <!--<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li>-->
            </ul>
            <form class="form-inline my-2 my-lg-0" type="get" action="{%url 'articles:search' %}" style="margin: 0">
                {% csrf_token %}
                <input id="search_box" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search_box">
                <button class="btn" type="submit" style="background-color: lightblue;">Search</button>
                
              </form>
          </div>
        </nav>


      {% block extra_js %}{% endblock extra_js %}

templates/index.html
{% include 'base.html' %}



CLIQUE SUR UNE DES OPTIONS SUR LA BARRE DE MENU !